# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release development

on:
  push:
    branches: [ "main" ]

jobs:

  pre-release:
    name: "Release Development"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Install dependencies
      run: go get .

    - name: Install libraries
      run: sudo apt-get install -y brotli zopfli

    - name: Build
      run: |
        bash ./scripts/build.sh  
        bash ./scripts/build-wasm.sh main build zopfli brotli  
        bash ./scripts/build-wasm.sh helper build zopfli brotli  
        bash ./scripts/build-electron-helper.sh     
        cd ./bin
        (cd wasm/build; zip -r ../artifact-wasm.zip *)
        (cd electron-helper; zip -r ../artifact-electron-helper.zip *)
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "development"
          prerelease: true
          title: "Development Build"
          files: |
            ./bin/pandora-linux-*
            ./bin/pandora-windows-*
            ./bin/pandora-darwin-*
            ./bin/wasm/artifact-wasm.zip
            ./bin/artifact-electron-helper.zip
